### ISSUE TITLE
mejorar la ui/ux del chat bot en vivo e implemantar sdk de vercel ia

### ISSUE THREAD

**Issue by MranDvX** [EntrevistadorInteligente/si-client-app#41]
Yo no lo contrato, Ya me aburrio y ni dijo contraste (Comentario de un usuario)
Implementar chatbot en vivo versel sdk

![Image](https://github.com/user-attachments/assets/a1bc2883-8364-4594-8b70-bf6c7d9df0f3)

[sdk.vercel.ai](https://sdk.vercel.ai/docs/introduction)

**Comment by RevillaDev** [comment]
Se reviso el PR [#56](https://github.com/EntrevistadorInteligente/si-orchestrator/pull/56), validar la sugerencia de los importes.
